# Generated by Django 5.0.2 on 2024-02-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testDB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Результата')),
                ('result', models.CharField(max_length=50, verbose_name='Результат экзамена')),
            ],
        ),
    ]
