# Generated by Django 5.0.2 on 2024-02-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=50, verbose_name='ID Ученика')),
                ('school_code', models.IntegerField(verbose_name='Код школы')),
                ('class_number', models.IntegerField(verbose_name='Номер класса')),
                ('subject_code', models.IntegerField(verbose_name='Код предмета')),
                ('subject_name', models.CharField(max_length=30, verbose_name='Название предмета')),
                ('first_result', models.IntegerField(verbose_name='Первичный балл')),
                ('percent_result', models.IntegerField(verbose_name='Процент выполнения')),
                ('hundred_result', models.IntegerField(verbose_name='100 бальная шкала')),
                ('first_result_short', models.IntegerField(verbose_name='Первичный балл краткий ответ')),
                ('result_short', models.CharField(max_length=30, verbose_name='Оценка кратких ответов')),
                ('first_result_long', models.IntegerField(verbose_name='Первичный балл развернутый ответ')),
                ('result_long', models.CharField(max_length=50, verbose_name='Оценка развернутых ответов')),
                ('first_result_oral', models.IntegerField(verbose_name='Первичный балл устный ответ')),
                ('result_oral', models.CharField(max_length=50, verbose_name='Оценка устных ответов')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.AlterModelOptions(
            name='testdb',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
