# Generated by Django 5.0.2 on 2024-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdapp', '0002_data2018_alter_testdb_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data2018',
            name='class_number',
            field=models.CharField(max_length=5, verbose_name='Номер класса'),
        ),
    ]
